### ISSUE TITLE
[Keyboard Accessibility] Command Palette Access 

### ISSUE THREAD

**Issue by thorsummoner** [NickHatBoecker/CopyFilepathWithLineNumbers#1]
Would be great if you could add a command palette call to do the copy call <3

**Comment by NickHatBoecker** [comment]
Was added in [5e08dd4](https://github.com/clempat/CopyFilepathWithLineNumbers/commit/5e08dd41108f57d601105544cb20e052844ec627). Please try!

**Comment by thorsummoner** [comment]
I will be able to try this in about six hours, can't wait :)

**Comment by thorsummoner** [comment]
That works, I found the names a bit confusing though; is the "Copy Reference" really a "Copy Filepath From Git Root" sortof thing?

**Comment by NickHatBoecker** [comment]
"Copy Reference" is a relative path with line numbers, whereas "Copy Filepath" is an absolute path without line numbers and "Copy Filepath With Line Numbers" is an absolute path with line numbers.

What about renaming these three options to:
"Copy relative path (with line numbers)"
"Copy absolute path (with line numbers)"
"Copy absolute path (without line numbers)"
