### ISSUE TITLE
Copy relative file path

### ISSUE THREAD

**Issue by mradionov** [NickHatBoecker/CopyFilepathWithLineNumbers#2]
It would be nice to be able to copy file path with line number relative to currently open project directory.

**Comment by NickHatBoecker** [comment]
Was solved in [04e2c1f](https://github.com/clempat/CopyFilepathWithLineNumbers/commit/94e2c1f27964245db2315cc9fcc49e65d6e66175). Please try!

**Comment by mradionov** [comment]
Works great, thanks!
